### ISSUE TITLE
Add enriched semver for non prod packages

### ISSUE THREAD

**Issue by monsieurleberre** [trakx/bump-version-action#1]
The current dotnet-utils has an extra step to gather branch information and build number, and add it to the package names.

The aim is to have incremental package numbers by branch, and make it easier to play with temporary packages as a developer.

Here it is:
https://github.com/trakx/dotnet-utils/blob/98da6601cda5ce9aa09039cbf0268677a2f85cb4/.github/workflows/publish.nuget.yml#L65

It creates package names like this one
![image](https://user-images.githubusercontent.com/4638821/140752213-742b54c1-4570-4913-af40-a9508e222221.png)

Would it make sense to add that to this action ?

Thanks

**Comment by ygavrishov** [comment]
@monsieurleberre As I understand you, it's needed to keep an independent build number sequence for every branch.
As a sample:
0.2.7-branchOne.1.hash
0.2.7-branchOne.2.hash
0.2.7-branchTwo.1.hash
0.2.7-branchOne.3.hash
Did I understand you right?

**Comment by monsieurleberre** [comment]
Hey @ygavrishov the requirement came from the following issue: one is developing a new feature, and wants to know which package was produced after the other - on that same branch - to iterate on the changes after testing them.
The current code in dotnet-utils is not really caring about the independence of build numbers, as 
- the ordering of the packages is done alphabetically and the name of the branch should be enough to differentiate one package from another
- for the same branch, a later package will have a later build number, and thus won't be confused with a previous one
I hope that makes sense, please let me know if not :)

**Comment by ygavrishov** [comment]
bump-version-action@v5 does not care about independent build numbers for branches too but it already generates tags in style `major.minor.revision-branch-buildNumber-commitHash`.

For the last changes in index-repository it looks like:
```
0.1.7-historical-prices-persistence-62-f89c592
0.1.7-historical-prices-persistence-61-53280cf
0.1.7-historical-prices-persistence-60-f0a685c
0.1.7-historical-prices-persistence-59-474fed1
```
I can replace hyphens with dots and seems the ticket is done, right?

**Comment by ygavrishov** [comment]
Finally applied in all repositories.
